### ISSUE TITLE
Running project

### ISSUE THREAD

**Issue by youssefabc** [Orange-OpenSource/Orange-Boosted-Angular#10]
Hello,
I'm trying to start this application i follow the steps in the file read me
npm install (it's OK)
npm start (isn't OK) and i have this error:
#############################################################################
D:\Profiles\ymissaoui\Desktop\Workspaces\Orange-Boosted-Angular-master\node_modules\ajv\lib\ajv.js:95
    if (!v) throw new Error('no schema with key or ref "' + schemaKeyRef + '"');
            ^

Error: no schema with key or ref "http://json-schema.org/draft-04/schema#"
    at Ajv.validate (D:\Profiles\ymissaoui\Desktop\Workspaces\Orange-Boosted-Angular-master\node_modules\ajv\lib\ajv.js:95:19)
    at Ajv.validateSchema (D:\Profiles\ymissaoui\Desktop\Workspaces\Orange-Boosted-Angular-master\node_modules\ajv\lib\ajv.js:183:22)
    at Ajv._addSchema (D:\Profiles\ymissaoui\Desktop\Workspaces\Orange-Boosted-Angular-master\node_modules\ajv\lib\ajv.js:317:10)
    at Ajv.validate (D:\Profiles\ymissaoui\Desktop\Workspaces\Orange-Boosted-Angular-master\node_modules\ajv\lib\ajv.js:97:26)
    at validate (D:\Profiles\ymissaoui\Desktop\Workspaces\Orange-Boosted-Angular-master\node_modules\extract-text-webpack-plugin\schema\validator.js:8:20)
    at new ExtractTextPlugin (D:\Profiles\ymissaoui\Desktop\Workspaces\Orange-Boosted-Angular-master\node_modules\extract-text-webpack-plugin\index.js:125:3)
    at makeWebpackConfig (D:\Profiles\ymissaoui\Desktop\Workspaces\Orange-Boosted-Angular-master\webpack.config.js:201:7)
    at Object.<anonymous> (D:\Profiles\ymissaoui\Desktop\Workspaces\Orange-Boosted-Angular-master\webpack.config.js:243:2)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at requireConfig (D:\Profiles\ymissaoui\Desktop\Workspaces\Orange-Boosted-Angular-master\node_modules\webpack\bin\convert-argv.js:96:18)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ng-boosted@0.0.1 server: `webpack-dev-server --progress --profile --watch`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ng-boosted@0.0.1 server script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     d:\Profiles\ymissaoui\AppData\Roaming\npm-cache\_logs\2018-10-04T07_59_37_196Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ng-boosted@0.0.1 start: `npm run build:dist && npm run server`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ng-boosted@0.0.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     d:\Profiles\ymissaoui\AppData\Roaming\npm-cache\_logs\2018-10-04T07_59_37_251Z-debug.log
###########################################################################

Thanks for your help

**Comment by youssefabc** [comment]
Thanks @liyokuna 
It works :)
But it need Typscript version between 2.7.2 and 2.8.0
So i installed it using npm install typescript@2.7.2

**Comment by liyokuna** [comment]
Great ! Your welcome.
The next release will have the latest version of typescript.

**Comment by liyokuna** [comment]
um...
No. At the beginning, we didn't plan to use Angular CLI.
Honestly I don't know. We think also to add Angular-CLI to ng boosted.

**Comment by youssefabc** [comment]
So what do you think , if i want to generate new component or service i generate it manually?

**Comment by youssefabc** [comment]
I am trying to integrate angular cli :)
There is some packages to install in order to have both of them

**Comment by liyokuna** [comment]
oh ok :D It will be interesting to share your work.
It is in our plan to do the same.
